openapi: 3.0.0
info:
  title: ONDC Protocol API
  description: ONDC Protocol API
  version: 0.1.0-draft
security:
  - SubscriberAuth: []
paths:
  /report:
    post:
      tags:
        - ONDC Buyer App
        - ONDC Seller App
      description: Report issue
      requestBody:
        description: Affected party reports issue to party responsible for issue
        content:
          application/json:
            schema:
              type: object
              properties:
                context:
                  $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/ecosystem-fixes/core/v0/api/core.yaml#/components/schemas/Context'
                message:
                  type: object
                  properties:
                    issue:
                      $ref: '#/components/schemas/Issue'
              required:
                - context
                - message
      responses:
        '200':
          description: Acknowledgement of message received
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    properties:
                      ack:
                        $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/ecosystem-fixes/core/v0/api/core.yaml#/components/schemas/Ack'
                    required:
                      - ack
                  error:
                    $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/ecosystem-fixes/core/v0/api/core.yaml#/components/schemas/Error'
                required:
                  - message
  /on_report:
    post:
      tags:
        - ONDC Buyer App
        - ONDC Seller App
      description: Party responsible for issue provides response
      requestBody:
        description: Party responsible for issue provides response to affected party that raised issue
        content:
          application/json:
            schema:
              type: object
              properties:
                context:
                  $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/ecosystem-fixes/core/v0/api/core.yaml#/components/schemas/Context'
                message:
                  type: object
                  properties:
                    state:
                      $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/ecosystem-fixes/core/v0/api/core.yaml#/components/schemas/Issue/properties/state'
                error:
                  $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/ecosystem-fixes/core/v0/api/core.yaml#/components/schemas/Error'
      responses:
        '200':
          description: Acknowledgement of message received
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    properties:
                      ack:
                        $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/ecosystem-fixes/core/v0/api/core.yaml#/components/schemas/Ack'
                    required:
                        - ack
                  error:
                    $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/ecosystem-fixes/core/v0/api/core.yaml#/components/schemas/Error'
                required:
                  - message
components:
  securitySchemes:
    SubscriberAuth:
      type: apiKey
      in: header
      name: Authorization
      description: 'Signature of message body using Buyer App or Seller App subscriber''s signing public key. <br/><br/>Format:<br/><br/><code>Authorization : Signature keyId="{subscriber_id}|{unique_key_id}|{algorithm}",algorithm="ed25519",created="1606970629",expires="1607030629",headers="(created) (expires) digest",signature="Base64(signing string)"</code>'
  schemas:
    Issue:
      description: Describes an issue
      type: object
      properties:
        id:
          type: string
          description: issue id
        category_id:
          $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/ecosystem-fixes/core/v0/api/core.yaml#/components/schemas/Category/properties/id'
        order_id:
          type: string
          description: order id
        evidence:
          $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/ecosystem-fixes/core/v0/api/core.yaml#/components/schemas/Descriptor'
        created_for:
          $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/ecosystem-fixes/core/v0/api/core.yaml#/components/schemas/Context/properties/domain'
        created_by:
          type: string
          description: subscriber id for party that created issue
        state:
          $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/ecosystem-fixes/core/v0/api/core.yaml#/components/schemas/Descriptor'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - category_id
        - evidence
        - created_for
        - created_by
        - state
        - created_at
        - updated_at
