openapi: 3.0.0
info:
  title: Settlement Advice for Settlement Agency
  description: Settlement Agency API Specification
  version: 0.3.0-draft
security:
  - SubscriberAuth: []
paths:
  /settle:
    post:
      tags:
        - SettlementAgency
      description: settlement of payment for different receivers - called by RSP
      requestBody:
        description: RSP advising settlement agency to settle receiver payments
        content:
          application/json:
            schema:
              type: object
              properties:
                context:
                  $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/draft/core/v0/api/core.yaml#/components/schemas/Context'
                message:
                  type: object
                  properties:
                    settlement:
                      $ref: '#/components/schemas/Settlement'
              required:
                - context
                - message.settlement.settlements.payer_name
                - message.settlement.settlements.payer_address
                - message.settlement.settlements.payer_account_no
                - message.settlement.settlements.payer_bank_code
                - message.settlement.settlements.curr_type
                - message.settlement.settlements.amount
                - message.settlement.settlements.timestamp
                - message.settlement.settlements.payee_name
                - message.settlement.settlements.payee_address
                - message.settlement.settlements.payee_account_no
                - message.settlement.settlements.payee_bank_code
                - message.settlement.settlements.payment_type
                - message.settlement.settlements.purpose_code
                - message.settlement.settlements.payee_account_type
                - message.settlement.settlements.settlement_id
      responses:
        '200':
          description: Acknowledgement of message received
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    properties:
                      ack:
                        $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/draft/core/v0/api/core.yaml#/components/schemas/Ack'
                    required:
                      - ack
                  error:
                    $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/draft/core/v0/api/core.yaml#/components/schemas/Error'
                required:
                  - message

components:
  securitySchemes:
    SubscriberAuth:
      type: apiKey
      in: header
      name: Authorization
      description: 'Signature of message body using Collector or Receiver subscriber''s signing public key. <br/><br/>Format:<br/><br/><code>Authorization : Signature keyId="{subscriber_id}|{unique_key_id}|{algorithm}",algorithm="ed25519",created="1606970629",expires="1607030629",headers="(created) (expires) digest",signature="Base64(signing string)"</code>'
  schemas:
    Settlement:
      description: Settlement details
      type: object
      properties:
        settlements:
          type: array
          items:
            type: object
            properties:
              payer_name:
                type: string
                description: "Payer name"
                example: "“Example1 company Pvt. Ltd"
              payer_address:
                $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/draft/core/v0/api/core.yaml#/components/schemas/Address/properties/full'
              payer_account_no:
                type: number
                description: "Debit Account Number of the client, used when client maintains multiple debit accounts with bank"      
                example: 509424924294248
              payer_bank_code:
                type:  string
                description: "Bank Code of Payee e.g. IFSC code"
                example: “HDFC0000000”
              payer_virtual_payment_address:
                type: string
                pattern: '^([a-zA-Z0-9]{2,10})@([a-zA-Z0-9]{2,10})'
                example: "80abc@abctMh2h"
              curr_type: 
                $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/draft/core/v0/api/core.yaml#/components/schemas/Price/properties/currency'
              amount:
                $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/draft/core/v0/api/core.yaml#/components/schemas/Price'
              timestamp:
                type: string
                format: date-time
              payee_name:
                type: string
                description: "Payee name"
                example: "A to Z Printing Solutions Pvt. Ltd"
              payee_address:
                $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/draft/core/v0/api/core.yaml#/components/schemas/Address/properties/full'
              payee_account_no:
                type: string
                description: "Account number of the beneficiary which is to be credited. Without special charcters and can be alpha numeric"
              payee_bank_code:
                type:  string
                description: "Bank Code of Payee e.g. IFSC code"
              payee_virtual_payment_address:
                type: string
                pattern: '^([a-zA-Z0-9]{2,10})@([a-zA-Z0-9]{2,10})'
              payment_type:
                description: "Payment type allocated by the bank"
                enum:
                  - "01"
                  - "02"
                  - "03"
                  - "04"
                  - "05"
              purpose_code:
                type: string
                maxLength: 10
                description: "For RTGS / IFT transaction it should contain CMS and for NEFT it should be OTH"
                enum:
                  - "01"
                  - "02"
              payee_account_type:
                type: string
                description: "Type of Beneficiary Account"
                enum:
                - "01"
                - "02"
                - "03"
              remarks:
                $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/draft/core/v0/api/core.yaml#/components/schemas/Descriptor'
              settlement_id:
                type: string
                description: "Unique identifier for each settlement"
                example: "121313"
              state:
                type: string
                description: settlement state
                enum:
                  - "01"
                  - "02"
                  - "03"
              prev_settlement_reference_no:
                type: array
                description: "Array of all previous UTR references against which settlement for this order was done"
                example: ["1234ABCD","2345qwer"]
                items:
                  type: string
              settlement_reference_no:
                type: string
                description: "Reference number, incase of successful settlement"
                example: "3718683618631"
              error_code:
                type: string
                description: "Error Message Code, to be provided by bank. Only required if settlement_status = 03"
                enum:
                  - "01"
                  - "02"
                  - "03"
                  - "04"
              error_message:
                type: string
                description: Message for error on settlement. Only required if settlement_status = "03"
                example: "Account not active or not found"
            required:
              - payer_name
              - payer_address
              - payer_account_no
              - payer_bank_code
              - curr_type
              - amount
              - timestamp
              - payee_name
              - payee_address
              - payee_account_no
              - payee_bank_code
              - payment_type
              - purpose_code
              - payee_account_type
              - settlement_id
